website/website/Controllers/recipesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using website.Models;

namespace website.Controllers
{
    public class recipesController : Controller
    {
        private Models.tarifsitesiEntities1 db = new Models.tarifsitesiEntities1();

        // GET: recipes


        //public ActionResult Index()
        //{
        //    var recipes = db.recipes.Include(r => r.categories).Include(r => r.users);
        //    return View(recipes.ToList());
        //}

        public ActionResult Index(string aranacakKelime)
        {
            var yemekler= db.recipes.Include(r => r.categories).Include(r => r.users);
           
            return View(yemekler.ToList());
        }

        public ActionResult YemekAra(string Ara = null, string[] Employee = null)
        {
            int k = 0;
            int j = 0;

            var aranan = db.recipes.ToList();
            if(Ara!="")
            {
                aranan = db.recipes.Where(m => m.name.Contains(Ara)).ToList();
                var sql = db.Database.SqlQuery<comments>("Select * from comments").Where(i => i.meal_id == i.meal_id).ToList();
            }
            

            else if(Employee.Count()!=0)
            {
                for(k=0;k<Employee.Count();k++)
                {
                    string ara = Employee[k];
                    aranan = db.recipes.Where(m => m.material.Contains(ara)).ToList();
                    if(aranan.Count()==0)
                    {
                        break;
                    }

                    else
                    {
                        j += 1;
                    }
                }

                if(k==j)
                {
                    string ara1 = Employee[0];
                    string ara2 = Employee[1];
                    aranan = db.recipes.Where(m => m.material.Contains(ara1) 
                    && m.material.Contains(ara2)).ToList();
                    var sql = db.Database.SqlQuery<comments>("Select * from comments").Where(i => i.meal_id == i.meal_id).ToList();
                }
                
                
            }
            

            return View(aranan.OrderByDescending(m=>m.date));
        }

        // GET: recipes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            recipes recipes = db.recipes.Find(id);
            if (recipes == null)
            {
                return HttpNotFound();
            }
            users users = db.users.Find(recipes.user_id );
            ViewBag.name = users.name_sname;
            Session["uye_id"] = users.id;
            ViewBag.user_id = new SelectList(db.users, "id", "name_sname", recipes.user_id);
            ViewBag.Query = db.recipes.Find(id);
            DateTime baslamaTarihi = new DateTime(2014, 10, 01);
            DateTime bitisTarihi = new DateTime(2015, 12, 15);

            TimeSpan kalangun = bitisTarihi - baslamaTarihi;//Sonucu zaman olarak döndürür
            int toplamGun = Convert.ToInt32( kalangun.TotalDays);
            int year = toplamGun / 365;
            int month = (toplamGun%365)/30;
            int day = (toplamGun % 365)%30;
            ViewBag.year = year;
            ViewBag.month = month;
            ViewBag.day = day;
            return View(recipes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(string yorum, int? id)
        {
            id = 9;
            recipes tarifler = db.recipes.Find(id);
            try
            {
                comments comments = new comments();
                comments.meal_id = Convert.ToInt32(id);
                comments.user_id = Convert.ToInt32(Session["uye_id"]);
                comments.confirmation = true;
                comments.content = yorum;
                comments.date = DateTime.Now;
                db.comments.Add(comments);
                db.SaveChanges();
                TempData["alert"] = "<script>alert('Yorumunuz kaydedildi');</script>";
                
            }

            catch(Exception)
            {
                TempData["alert"] = "<script>alert('Hata Oluştu');</script>";
            }

            ViewBag.Query = db.recipes.Find(id);
            return RedirectToAction("Details", new { id = id});
        }

        [HttpPost]
        public JsonResult Yorum(string yorum, int id)
        {
            var userid = Session["uye_id"];
            if (yorum == null)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            db.comments.Add(new comments { user_id = Convert.ToInt32(userid), meal_id = id, content = yorum, date = DateTime.Now, confirmation = true });
            db.SaveChanges();
            return Json(false, JsonRequestBehavior.AllowGet);
        }

        // GET: recipes/Create
        public ActionResult Create()
        {
            ViewBag.categori_id = new SelectList(db.categories, "id", "name");
            ViewBag.user_id = new SelectList(db.users, "id", "name_sname");
            return View();
        }

        // POST: recipes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(recipes recipes)
        {
            //if (ResimDosya != null)
            //{
            //    foreach (var item in ResimDosya)
            //    {
            //        item.SaveAs(Server.MapPath("~/Content/img/" + item.FileName));
            //        recipes.image = item.FileName;
            //    }
            //}
            if (ModelState.IsValid)
            {
                var userid = Session["uye_id"];
                recipes.user_id = Convert.ToInt32(userid);
                recipes.date = DateTime.Now;
                recipes.comments = null;
                db.recipes.Add(recipes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categori_id = new SelectList(db.categories, "id", "name", recipes.categori_id);
            ViewBag.user_id = new SelectList(db.users, "id", "name_sname", recipes.user_id);
            return View(recipes);
        }

        // GET: recipes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            recipes recipes = db.recipes.Find(id);
            if (recipes == null)
            {
                return HttpNotFound();
            }
            ViewBag.categori_id = new SelectList(db.categories, "id", "name", recipes.categori_id);
            ViewBag.user_id = new SelectList(db.users, "id", "name_sname", recipes.user_id);
            return View(recipes);
        }

        // POST: recipes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,material,praparation,image,date,point,categori_id,user_id,video")] recipes recipes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recipes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categori_id = new SelectList(db.categories, "id", "name", recipes.categori_id);
            ViewBag.user_id = new SelectList(db.users, "id", "name_sname", recipes.user_id);
            return View(recipes);
        }

        // GET: recipes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            recipes recipes = db.recipes.Find(id);
            if (recipes == null)
            {
                return HttpNotFound();
            }
            return View(recipes);
        }

        // POST: recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            recipes recipes = db.recipes.Find(id);
            db.recipes.Remove(recipes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

website/website/Views/recipes/Create.cshtml
@model website.Models.recipes
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "recipes", FormMethod.Post, new { enctype = "multpart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tarif Ekle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.material, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.TextAreaFor(model => model.material, 10, 97, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.material, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.preparation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.preparation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.preparation, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.categori_id, "Kategoriler", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                @Html.DropDownList("categori_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categori_id, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-12">
                <input type="file" multiple name="ResimDosya" id="ResimDosya" class="form-control" /> <br />
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Tarifi Gönder" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

website/website/Views/recipes/Delete.cshtml
@model website.Models.recipes

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>recipes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.material)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.material)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.praparation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.praparation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.point)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.point)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.video)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.video)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categories.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categories.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.users.name_sname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.users.name_sname)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

website/website/Views/recipes/Details.cshtml
@model website.Models.recipes
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using website.Models
@{recipes recipes = ViewBag.Query;}
<div class="container col-10" style="margin-bottom:20px;">

    @if (recipes.image != null)
    {
        <img src="~/Content/img/@recipes.image" style="width:600px;height:400px;" />
    }



    <h3 class="kutu1" style="color:darkred">@recipes.name</h3>

    <h4 style="color:black;font-size:large; font-weight:400;">@recipes.name İçin Malzemeler</h4>

    @*<div class="tr" style="background-color:#f1f1f1;">
        <div class="td">@Html.Partial("_VoteShow", Model.Vote)</div>
        <div class="td">@Html.Partial("_VoteNow", Model)</div>
    </div>*@

    <p>@Html.Raw(recipes.material)</p>
    <h4 style="color:black;font-size:large; font-weight:400;">@recipes.name Hazırlanışı</h4>
    <h6>@Html.Raw(recipes.preparation) </h6>
    <h4>Tarif Sahibi: @ViewBag.name</h4>

    @* Yorumlar*@
    <div style="height:300px; background-color:white; margin:20px 0 0 0; padding:5px; border-color:#4e73df;border-style: solid; border-width: 5px;">
        <div style="width:160px;height:30px;border-radius:5px;background-color:#4e73df;">
            <h5>Yorum Gönder</h5>
        </div>
        <br />


        @using (Html.BeginForm("Details", "recipes", FormMethod.Post))
        {
            if (Session["user"] == null)
            {
                <p>Yemek tariflerine yorum yapabilmek için <a href="/Home/Login" style="color:darkred;">üye girişi</a> yapmalısınız. </p>
            }

            @Html.AntiForgeryToken()
            <div class="form-group">
                <textarea id="yorum" name="yorum" class="form-control" rows="3"></textarea>
            </div>
            if (Session["user"] == null)
            {
                <a href="~/Home/Login"><input type="button" value="Giriş Yap" class="btn btn-primary" /></a>
                <a href="~/Home/Register"><input type="button" value="Üye Ol" class="btn btn-primary" /></a>
            }
            else
            {
                <a href="~/recipes/Details?id=@recipes.id"> <input id="gonder" name="id" type="submit" value="Gönder" class="btn btn-primary" /></a>
            }
            @Html.Raw(TempData["alert"]);
        }

    </div>

    <table class="table-primary col-12" style="border-color:#4e73df;border-style: solid; border-width: 5px;">
        <td>
            @if (recipes.comments.ToList().Count == 0)
            {
                <h5 style="color:darkred">Bu tarife henüz yorum yapılmamış. İlk yorum yapan siz olun!</h5>
            }
            else
            {
                <br>
                <h4 style="color:darkred;text-align:center;">Yorumlar</h4>
                <br />
                foreach (var item in recipes.comments.ToList())
                {
                <div style="border:solid 1px;">
                    <div style="border:solid 1px;">
                        <a class="pull-left" href="#" style="position:relative;">
                            <h5>
                                @item.users.name_sname
                                <img class="img-profile rounded-circle" style="width:50px;" src="~/Content/img/users/@item.users.image" alt="@item.users.name_sname" />
                                <small>@ViewBag.year yıl @ViewBag.month ay @ViewBag.day gün önce</small>
                            </h5>
                        </a>
                    </div>
                    
                    <br />
                    <p>@item.content</p>
                </div>
                <br />
                }
            }
        </td>
        <br />
        </table>
</div>

<script src="~/Scripts/js/jquery.min.js">

</script>

website/website/Views/recipes/Edit.cshtml
@model website.Models.recipes

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>recipes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.material, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.material, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.material, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.praparation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.praparation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.praparation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.point, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.point, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.point, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.categori_id, "categori_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("categori_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categori_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, "user_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.video, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.video, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.video, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

website/website/Views/recipes/Index.cshtml
@model IEnumerable<website.Models.recipes>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid  text-center">
    <h4 style="color:darkred">Tarifler</h4>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="bg-primary"></div>
            <div class="col-4" style="height:300px; background-color:white; margin:20px 0 0 0; padding:5px; border-color:white;border-style: solid; border-width: 5px;">
                <a href="~/recipes/Details?id=@item.id"><img src="~/Content/img/@item.image" style="width:80%; height:70%;" /></a>
                <a href="~/recipes/Details?id=@item.id"><h5 class="kutu1">@item.name</h5></a>
                <h5 class="kutu1">@item.users.name_sname</h5>
            </div>
            
        }
    </div>
</div>

website/website/Views/recipes/YemekAra.cshtml
@model IEnumerable<website.Models.recipes>

@{
    ViewBag.Title = "Ara";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="color:darkred">Aradığınız İçerikteki Sonuçlar</h3>
<div class="col-md-8">

</div>
<table class="table">

@foreach (var item in Model) {
    <tr rowspan="3">
        <td>
            <a href="~/recipes/Details?id=@item.id">
                <img class="img-thumbnail img-fluid" width="150px;" src="~/Content/img/@item.image" />
                </a>
        </td>
        <td>
            <a href="~/recipes/Details?id=@item.id">
                @Html.DisplayFor(modelItem => item.name)
            </a><br />
                <a href="~/users/Details?id=@item.user_id">
                    @Html.DisplayFor(modelItem => item.users.name_sname)<br /></a>
                    @Html.DisplayFor(modelItem => item.comments.Count) yorum<br />
                    @*@Html.Partial("_VoteShow", item.Vote)*@ 

</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
}

</table>